import 'dart:io';

class IconPackGenerationConfig {
  final String inputPath;
  final String outputPath;
  final String flutterImport;
  final String iconAccessor;
  final String outputVariableName;
  final String iconPackValue;

  const IconPackGenerationConfig({
    required this.inputPath,
    required this.outputPath,
    required this.flutterImport,
    required this.iconAccessor,
    required this.outputVariableName,
    required this.iconPackValue,
  });
}

Future<void> main() async {
  final generatorDirectory = File.fromUri(Platform.script).parent.path;
  final projectRoot = Directory(generatorDirectory).parent.path;

  final configs = <IconPackGenerationConfig>[
    IconPackGenerationConfig(
      inputPath: '$generatorDirectory/MaterialIcons.dart',
      outputPath: '$projectRoot/lib/core/generated/material_icon_pack.dart',
      flutterImport: 'package:flutter/material.dart',
      iconAccessor: 'Icons',
      outputVariableName: 'materialIconEntries',
      iconPackValue: 'IconPack.material',
    ),
    IconPackGenerationConfig(
      inputPath: '$generatorDirectory/CupertinoIcons.dart',
      outputPath: '$projectRoot/lib/core/generated/cupertino_icon_pack.dart',
      flutterImport: 'package:flutter/cupertino.dart',
      iconAccessor: 'CupertinoIcons',
      outputVariableName: 'cupertinoIconEntries',
      iconPackValue: 'IconPack.cupertino',
    ),
  ];

  for (final config in configs) {
    await generateIconPackFile(config);
  }
}

Future<void> generateIconPackFile(IconPackGenerationConfig config) async {
  final inputFile = File(config.inputPath);
  final outputFile = File(config.outputPath);

  if (!await inputFile.exists()) {
    stderr.writeln('Input file not found: ${inputFile.path}');
    exitCode = 1;
    return;
  }

  final source = await inputFile.readAsString();
  final names = _extractIconNames(source);

  if (names.isEmpty) {
    stderr.writeln('No icon constants found in ${inputFile.path}');
    exitCode = 1;
    return;
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('// Generated by tool/icon_pack_generator.dart')
    ..writeln()
    ..writeln("import '${config.flutterImport}';")
    ..writeln("import 'package:flutter_translator/core/app_icon_entry.dart';")
    ..writeln()
    ..writeln('const ${config.outputVariableName} = <AppIconEntry>[');

  for (final name in names) {
    buffer.writeln('  AppIconEntry(');
    buffer.writeln("    key: '$name',");
    buffer.writeln("    reference: '${config.iconAccessor}.$name',");
    buffer.writeln('    iconData: ${config.iconAccessor}.$name,');
    buffer.writeln('    pack: ${config.iconPackValue},');
    buffer.writeln('  ),');
  }

  buffer.writeln('];');

  await outputFile.create(recursive: true);
  await outputFile.writeAsString(buffer.toString());

  stdout.writeln(
    'Generated ${names.length} icon entries to ${outputFile.path}',
  );
}

List<String> _extractIconNames(String source) {
  final regex = RegExp(
    r'static const IconData\s+([a-zA-Z0-9_]+)\s*=\s*IconData\(',
    multiLine: true,
  );

  final names = <String>[];
  for (final match in regex.allMatches(source)) {
    final name = match.group(1);
    if (name == null || name.isEmpty) {
      continue;
    }
    names.add(name);
  }

  return names.toSet().toList()..sort();
}
